myapp/Models/ErrorViewModel.cs
namespace myapp.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

myapp/Models/Formulario.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;


namespace myapp.Models
{
    public class Formulario
    {
         [Display(Name = "First Name", Prompt = "Enter first Name")]
        public string? firstName {get; set;}
        
        [Display(Name = "Last Name", Prompt = "Enter Last Name")]
        public string? lastName {get; set;}

        [Display(Name = "Job Title", Prompt = "Enter your job Title")]
        public string? jobTitle {get; set;}   

        [Display(Name = "Highest level of education")]
        public string? level {get; set;}
       
       [Display(Name = "Sex")]
        public string? sex {get; set;}

        [Display(Name = "Years of experience:")]
        public string? years {get; set;}

        [Display(Name = "Date:")]
        [DataType(DataType.Date)]
        public string? date {get; set;}
    }
}

myapp/Controllers/FormularioController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using myapp.Models;

namespace myapp.Controllers
{
 
    public class FormularioController : Controller
    {
        private readonly ILogger<FormularioController> _logger;

        public FormularioController(ILogger<FormularioController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
         public IActionResult create(Formulario objFormulario)
        {

            ViewData["Message"] = "Thanks for submitting your form";
            ViewData["Message01"] = "First Name:"+ objFormulario.firstName;
            ViewData["Message02"] = "Last Name:"+ objFormulario.lastName;
            ViewData["Message03"] = "Job Title:"+ objFormulario.jobTitle;
            ViewData["Message04"] = "Highest level of education:"+ objFormulario.level;
            ViewData["Message05"] = "Sex:"+ objFormulario.sex;
            ViewData["Message06"] = "Years of experience:"+ objFormulario.years;
            ViewData["Message07"] = "Date:"+ objFormulario.date;
            return View("success");
            
        }



        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

myapp/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using myapp.Models;

namespace myapp.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

myapp/Views/Formulario/index.cshtml
@model myapp.Models.Formulario


<div >
   <strong><h1 class="display-4">COMPLETE WEB FORM:</h1></strong> 
    <form asp-controller="Formulario" asp-action="Create">
       
      <div asp-validation-summary="ModelOnly" class="text-danger"></div>
       <strong> <label asp-for="firstName" class="control-label"></label></strong><br>
        <input asp-for="firstName" class="col-sm-8 col-sm-offset-2" /> <br>

        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
       <strong><label asp-for="lastName" class="control-label"></label></strong><br>
        <input asp-for="lastName" class="col-sm-8 col-sm-offset-2" /> <br>
      
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
       <strong> <label asp-for="jobTitle" class="control-label"></label> </strong><br>
        <input asp-for="jobTitle" class="col-sm-8 col-sm-offset-2" /> <br>

        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
       <strong><label asp-for="level" class="control-label"></label> </strong>
            <br> 
           <input type="radio" asp-for="level" value="High School" >
           <label >High School</label><br> 
           <input type="radio" asp-for="level" value="College">
           <label >College    </label><br> 
           <input type="radio" asp-for="level" value="Grad School" >
           <label >Grad School</label> <br> 
        
        
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
       <strong><label asp-for="sex" class="control-label"></label> </strong>   
            <div class="form-check" >
                <input class="form-check-input"asp-for="sex" type="checkbox" value="Male">
                <label> Male</label>
            </div> 
            <div class="form-check" >
                <input class="form-check-input"  asp-for="sex" type="checkbox" value="Female">
                <label> Female</label>
            </div> 
            <div class="form-check" >
                <input class="form-check-input" asp-for="sex" type="checkbox" value=" Prefer not to say">
                <label> Prefer not to say</label>
            </div> 

         <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <strong> <label asp-for="years" class="control-label"></label></strong> <br>   
            <select asp-for="years" class="col-sm-8 col-sm-offset-2" > 
                <option value="NO OPTION">SELECT AN OPTION...</option>
                <option value="0-1">0-1</option>
                <option value="2-4">2-4</option>
                <option value="5-9">5-9</option>
                <option value="10+">10 +</option>
            </select>
          <br>
         <div asp-validation-summary="ModelOnly" class="text-danger"></div>
       <strong>  <label asp-for="date" class="control-label"></label></strong> <br>    
      <input  asp-for="date" type="date"  asp-format="{0:yyyy-MM-dd}"> <br>

       <br> <button type="submit" class="btn btn-primary">SUBMIT</button> <br>
    </form>


    <br><br>
   
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

myapp/Views/Formulario/success.cshtml
 
 @model myapp.Models.Formulario



 <strong><h1 align="center" >@ViewData["Message"]</h1></strong>

<h06 >@ViewData["Message01"]</h6> <br>
<h06 >@ViewData["Message02"]</h6> <br>
<h06 >@ViewData["Message03"]</h6> <br>
<h06 >@ViewData["Message04"]</h6> <br>
<h06 >@ViewData["Message05"]</h6> <br>
<h06 >@ViewData["Message06"]</h6> <br>
<h06 >@ViewData["Message07"]</h6> <br>

myapp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">PROBANDO CAMBIOS DE RAMA</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

myapp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - myapp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/myapp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FORMS</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                       
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Formulario" asp-action="Index">FORMY</a>
                        </li> 
                                           
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                       
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - myapp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>